from src.routes.plug import plug
from src.routes.auth import auth
from src.routes.demo.auth import demo_auth
from src.routes.demo.context_base import demo_context_base
from src.routes.payment import payment
from src.routes.context_base import context_base
from src.routes.admin.plug import admin_plug
from src.routes.admin.context_base import admin_context_base
from src.routes.admin.subscription import admin_subscription
from src.routes.admin.user import admin_user
from src.routes.live_demo import live_demo
from src.routes.image import image
from src.routes.subscription import subscription
from src.routes.ws import socketio
from src.routes.user import user
from src.routes.client import client
from src.routes.history import history
from src.routes.guest import guest
from src.routes.message import message
from src.routes.ws import websocket
